# Generated by Django 4.2.7 on 2023-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(default='1204e3e5-c366-4b87-88c7-399c004a337b', max_length=255, unique=True),
        ),
    ]
