# Generated by Django 4.2.7 on 2023-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0005_alter_profile_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('pemula', 'Pemula'), ('menengah', 'Menengah'), ('expert', 'Expert')], default='programmer-fulltime', max_length=30),
        ),
    ]
