# Generated by Django 4.2.7 on 2023-12-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0006_student_address_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profesi',
            field=models.CharField(choices=[('programmer-fulltime', 'Programmer-Fulltime'), ('programmer-freelancer', 'Programmer-Freelancer'), ('non-programmer', 'Non-Programmer')], default='programmer-fulltime', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('pemula', 'Pemula'), ('menengah', 'Menengah'), ('expert', 'Expert')], default='pemula', max_length=30),
        ),
    ]
