# Generated by Django 4.2.7 on 2023-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0007_student_profesi_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
