# Generated by Django 4.2.7 on 2023-12-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0010_alter_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
