# Generated by Django 4.2.7 on 2023-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0011_course_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.AddField(
            model_name='student',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
