# Generated by Django 4.2.5 on 2023-12-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0012_remove_course_owner_student_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kelasku',
            field=models.ManyToManyField(blank=True, to='kelas_programming.class'),
        ),
    ]
