# Generated by Django 4.2.7 on 2023-12-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0014_pickclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PickClass',
            new_name='Payment',
        ),
    ]
