# Generated by Django 4.2.7 on 2023-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0015_rename_pickclass_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='My Class', max_length=120, verbose_name='My Class'),
            preserve_default=False,
        ),
    ]
