# Generated by Django 4.2.7 on 2024-01-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0017_remove_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='definition',
            field=models.TextField(default='ini adalah contoh default deskripsi', verbose_name='Definisi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.CharField(max_length=120, verbose_name='Language'),
        ),
    ]
