# Generated by Django 4.2.7 on 2024-01-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0018_class_definition_alter_class_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='class_photo/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='class',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='class_video/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='class',
            name='definition',
            field=models.TextField(verbose_name='Definition'),
        ),
    ]
