# Generated by Django 5.0.1 on 2024-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_programming', '0019_class_photo_class_video_alter_class_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
